export const metadata = { title: "Privacy Policy" }

export default function PrivacyPage() {
  return (
    <div className="pt-24 pb-20 px-4 sm:px-6">
      <div className="max-w-3xl mx-auto">
        <h1 className="text-white text-3xl font-semibold mb-2">Privacy Policy</h1>
        <p className="text-muted text-sm mb-10">Last updated: {new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}</p>

        {[
          {
            title: "Information We Collect",
            body: "We collect information you provide directly: your name, email address, business name, location, and website URL. We also collect usage data, audit results, and performance metrics generated by the Service.",
          },
          {
            title: "Google API User Data",
            body: "When you connect your Google Business Profile, we access data through the Google My Business API. This data is used exclusively to post updates and retrieve performance metrics for your business. We do not sell, transfer, or use this data for advertising. Our use complies with the Google API Services User Data Policy. You can revoke Google access at any time from your Google account settings.",
          },
          {
            title: "How We Use Your Information",
            body: "We use your information to provide and improve the Service, generate content specific to your business, send transactional emails (audit results, weekly reports, billing notices), and troubleshoot issues.",
          },
          {
            title: "Data Sharing",
            body: "We do not sell your personal information. We share data only with: (a) service providers who help us operate the platform (Clerk for authentication, Stripe for payments, Railway for hosting, Resend for email, Anthropic for AI services), and (b) when required by law.",
          },
          {
            title: "AI-Generated Content",
            body: "Content generated for your business is produced using the Anthropic Claude API. Your business information is sent to Anthropic's API to generate content. Anthropic's privacy policy governs their use of this data. We do not use your data to train AI models.",
          },
          {
            title: "Data Retention",
            body: "We retain your data for as long as your account is active. After account deletion, we delete your personal data within 30 days. Audit history and generated content may be retained in anonymized form for up to 2 years for service improvement.",
          },
          {
            title: "Your Rights",
            body: "You may request access to, correction of, or deletion of your personal data at any time by emailing privacy@alphaa.app. We will respond within 30 days.",
          },
          {
            title: "Contact",
            body: "Privacy questions? Email privacy@alphaa.app.",
          },
        ].map((s) => (
          <div key={s.title} className="mb-8">
            <h2 className="text-white font-semibold text-lg mb-2">{s.title}</h2>
            <p className="text-muted text-sm leading-relaxed">{s.body}</p>
          </div>
        ))}
      </div>
    </div>
  )
}
